### ISSUE TITLE
add state management and protected routes

### ISSUE THREAD

**Issue by TejasNasre** [nexmeet/nexmeet#1]
Add state management and protected routes
- use zustand
- make protected routes
- protect the routes in main file using react-router
- any thing you want to add you can

Make sure to make PR on dev branch

**Comment by eduanmoldeep** [comment]
Do we have a new design figma file? or we replicating same design?

**Comment by TejasNasre** [comment]
We have figma file new one

**Comment by TejasNasre** [comment]
issue completed closing issue
