### ISSUE TITLE
design components 

### ISSUE THREAD

**Issue by TejasNasre** [nexmeet/nexmeet#2]
We have a figma file use that to make components in react use tailwind and shadcn structures

https://www.figma.com/design/ywxfYNYaOzZgPGyZi3WQ7j/NextMeet?node-id=141-294&t=zC0VjvYMyEr1WNPW-1

This is the figma file, 
1. Components are in the 'components' page
2. Finalised and approved pages are in 'Final pages'
3. I will mark components and pages as 'ready for dev'

**Comment by Aarshit-33** [comment]
I would be happy to help by creating React components based on the above designs utilizing Tailwind CSS and ShadCN structures. Tell me which pages or components are "ready for dev," and I'll start to code.

**Comment by TejasNasre** [comment]
yeah will send the conformation for the design which are "ready for dev"

**Comment by TejasNasre** [comment]
@Aarshit-33 ishad will help you for component thing I wrote code for navbar and hero page after that blue component you can build

**Comment by IshadP** [comment]
@Aarshit-33 
![Screenshot 2024-12-20 135154](https://github.com/user-attachments/assets/1cbbb2ba-aaf4-450f-aad9-fbd80e68aee5)
The components and pages marked with this icon at the top-right are considered 'ready for development'.

**Comment by Aarshit-33** [comment]
https://github.com/user-attachments/assets/4c47b76c-dd6d-4bf7-b6e9-dd6761d9f88b


Demo for the implementation of the FAQ Component, I have raised a PR for it, if you find it useful then merge it. @TejasNasre

**Comment by TejasNasre** [comment]
Great will check and merge soon
