### ISSUE TITLE
fix navbar

### ISSUE THREAD

**Issue by TejasNasre** [nexmeet/nexmeet#3]
i created a navbar but i want it sticky not fixed and when i got sticky the bg should transparent for the navbar bg

**Comment by Aarshit-33** [comment]
assign this issue to me. I'll get it done

**Comment by TejasNasre** [comment]
before making PR please have a small video here

**Comment by Aarshit-33** [comment]
> before making PR please have a small video here also do changes in dev branch

I'll take care from the next time

**Comment by Ishpreet01** [comment]
Hi, Can you assign this issue to me? I  am new to open source and would like to work on this.

**Comment by TejasNasre** [comment]
@Ishpreet01 hey thanks for your interest but the issue is completed look for other issues
