### ISSUE TITLE
update readme

### ISSUE THREAD

**Issue by TejasNasre** [nexmeet/nexmeet#8]
Update the whole readme doc with all the details 

Refer : https://github.com/TejasNasre/nexmeet

**Comment by TejasNasre** [comment]
hey @Ishpreet01 you are in nexmeet community grp ?

**Comment by Ishpreet01** [comment]
@TejasNasre No not yet

**Comment by Ishpreet01** [comment]
Can you please what changes I need to make in the readme file? And from where will I get to know that these changes have to be made?

**Comment by TejasNasre** [comment]
Take refrence from https://github.com/TejasNasre/nexmeet

And we have community so join that community : https://chat.whatsapp.com/HD7kdkjzSP8Lf1nY6iTpnN

We have meet at 9.30pm today and join contributor grp
